UW/MSUN/Packer set PType_Bits 8
UW/MSUN/Packer set List_of_hops_length_Bits 8
UW/MSUN/Packer set Pointer_to_list_of_hops_Bits 8
UW/MSUN/Packer set List_of_hops_Entry_Bits 8
UW/MSUN/Packer set Quality_Bits 8
UW/MSUN/Packer set SAddr_Bits 8
UW/MSUN/Packer set Uid_Bits 8
UW/MSUN/Packer set TTL_Bits 8
UW/MSUN/Packer set debug_ 0
